from pathlib import Path
from typing import Protocol


class Provider(Protocol):
    async def list_pull_requests(self) -> list[dict]: ...
    async def get_pull_request(self, pr_id: int) -> dict: ...
    async def get_changed_files(self, pr_id: int) -> list[str]: ...
    async def get_clone_url(self) -> str: ...
    async def post_comment(self, pr_id: int, text: str) -> None: ...
